name: "MAIA - My AI Assistant"
version: "1.0.0"
slug: "maia"
description: "Advanced Home Assistant Voice and Vision Integration"
url: "https://github.com/kimasplund/maia"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
map:
  - share:rw
  - config:rw
services:
  - "mqtt:need"
  - name: valkey
    image: valkey/valkey:8-alpine3.20
    volumes:
      - /data/valkey:/data
    ports:
      - "7000:7000"
    healthcheck:
      test: ["CMD", "valkey", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5
    init: true
    privileged: false
    network_mode: host
    restart: unless-stopped
  - name: postgis
    image: "postgis/postgis:17-3.5-alpine"
    environment:
      POSTGRES_USER: "!secret postgres_user"
      POSTGRES_PASSWORD: "!secret postgres_password"
      POSTGRES_DB: "!secret postgres_db"
    volumes:
      - /data/postgis:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U !secret postgres_user -d !secret postgres_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    init: true
    privileged: false
    network_mode: host
    restart: unless-stopped
discovery:
  - mqtt
panel_icon: mdi:robot
panel_title: MAIA
panel_admin: true
ingress: true
ingress_port: 8000
host_network: false
ports:
  8000/tcp: 8000
  5432/tcp: 5432 # PostGIS port
ports_description:
  8000/tcp: "Web interface"
  5432/tcp: "PostGIS database"
hassio_api: true
hassio_role: manager
homeassistant_api: true
options:
  mqtt:
    broker: "core-mosquitto"
    port: 1883
    username: ""
    password: ""
  database:
    postgres_user: "maia"
    postgres_password: ""
    postgres_db: "maia"
  camera:
    use_gpu: false
    model_type: "hog"
    tolerance: 0.6
    batch_processing: true
    max_batch_size: 32
    thread_limits:
      openmp: 4
      blas: 2
  voice:
    recognition_engine: "google"
    language: "en-US"
    enable_noise_reduction: true
    thread_limits:
      openmp: 2
      blas: 1
  websocket:
    host: "0.0.0.0"
  ble_tracking:
    enabled: true
    scan_interval: 5
    min_rssi: -90
    position_update_interval: 1
schema:
  mqtt:
    broker: str
    port: port
    username: str
    password: password
  database:
    postgres_user: str
    postgres_password: password
    postgres_db: str
  camera:
    use_gpu: bool
    model_type: list(hog|cnn)
    tolerance: float(0,1)
    batch_processing: bool
    max_batch_size: int(1,64)
    thread_limits:
      openmp: int(1,8)
      blas: int(1,4)
  voice:
    recognition_engine: list(google|sphinx|vosk)
    language: str
    enable_noise_reduction: bool
    thread_limits:
      openmp: int(1,4)
      blas: int(1,2)
  websocket:
    host: str
  ble_tracking:
    enabled: bool
    scan_interval: int(1,60)
    min_rssi: int(-100,-40)
    position_update_interval: int(1,60)
image: "ghcr.io/{repository}/maia" 