name: "MAIA - AI Assistant"
version: "1.0.0"
slug: "maia"
description: "MAIA (Modular AI Assistant) - A powerful AI assistant for Home Assistant with face recognition and voice control"
url: "https://github.com/yourusername/ha_maia"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
boot: auto
init: false
map:
  - share:rw
  - config:rw
ports:
  8765/tcp: 8765
  6379/tcp: 6379
ports_description:
  8765/tcp: "WebSocket server port"
  6379/tcp: "Redis database port"
options:
  camera:
    use_gpu: false
    model_type: "hog"
    tolerance: 0.6
    batch_processing: true
    max_batch_size: 32
    thread_limits:
      openmp: 4
      blas: 2
  voice:
    recognition_engine: "sphinx"
    language: "en-US"
    enable_noise_reduction: true
    thread_limits:
      openmp: 2
      blas: 1
  websocket:
    host: "0.0.0.0"
    port: 8765
  database:
    host: "localhost"
    port: 6379
schema:
  camera:
    use_gpu: bool
    model_type: str
    tolerance: float
    batch_processing: bool
    max_batch_size: int
    thread_limits:
      openmp: int
      blas: int
  voice:
    recognition_engine: str
    language: str
    enable_noise_reduction: bool
    thread_limits:
      openmp: int
      blas: int
  websocket:
    host: str
    port: int
  database:
    host: str
    port: int 