version: '3.8'

services:
  maia:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SUPERVISOR_URL=${HA_URL}
      - SUPERVISOR_TOKEN=${HA_TOKEN}
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
      - MQTT_USERNAME=maia
      - MQTT_PASSWORD=maia
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=maia
      - POSTGRES_USER=maia
      - POSTGRES_PASSWORD=maia
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
    volumes:
      - ./data:/app/data
    depends_on:
      - postgres
      - mosquitto
      - valkey

  postgres:
    image: postgis/postgis:17-3.5-alpine
    environment:
      - POSTGRES_DB=maia
      - POSTGRES_USER=maia
      - POSTGRES_PASSWORD=maia
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mosquitto:
    image: eclipse-mosquitto:latest
    volumes:
      - ./config/mosquitto:/mosquitto/config
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
    entrypoint: sh -c "
      echo 'maia:maia' > /mosquitto/config/passwd &&
      mosquitto_passwd -U /mosquitto/config/passwd &&
      mosquitto -c /mosquitto/config/mosquitto.conf"

  valkey:
    image: valkey/valkey:alpine3.20
    ports:
      - "6379:6379"
    volumes:
      - valkey_data:/data

volumes:
  postgres_data:
  mosquitto_data:
  mosquitto_log:
  valkey_data: 